name: Run autotests


on:
  worlklow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        required: true
        type: choice
        default: all
        options:
          - all

jobs:
  run-tests:
    runs-on: windows-10
    name: Tests
    steps:
      - name: Copy source code
        uses: actions/checkout@v4
      - name: Set up Python env
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirement.txt
      - name: Run tests
        run: pytest -v
      
